#include "Gpio.h"

uint32_t Counter = 0;

int main(void){
	GPIO_PortInit(GPIOG, GPIO_PIN_6, GPIO_MODE_OUTPUT, GPIO_PUSH_PULL, GPIO_HIGH_SPEED, GPIO_PULLUP);
	GPIO_PortInit(GPIOK, GPIO_PIN_3, GPIO_MODE_OUTPUT, GPIO_PUSH_PULL, GPIO_HIGH_SPEED, GPIO_PULLUP);
	GPIO_PortInit(GPIOD, GPIO_PIN_4|GPIO_PIN_5, GPIO_MODE_OUTPUT, GPIO_PUSH_PULL, GPIO_HIGH_SPEED, GPIO_PULLUP);
	while (1){
		GPIO_WritePin(GPIOG,GPIO_PIN_6, GPIO_PIN_SET);
		GPIO_WritePin(GPIOK,GPIO_PIN_3, GPIO_PIN_SET);
		GPIO_WritePin(GPIOD,GPIO_PIN_4|GPIO_PIN_5, GPIO_PIN_SET);
		while(Counter<200000)Counter++;
		if(Counter>=200000)Counter=0;
		GPIO_WritePin(GPIOG,GPIO_PIN_6, GPIO_PIN_RESET);
		GPIO_WritePin(GPIOK,GPIO_PIN_3, GPIO_PIN_RESET);
		GPIO_WritePin(GPIOD,GPIO_PIN_4|GPIO_PIN_5, GPIO_PIN_RESET);
		while(Counter<200000)Counter++;
		if(Counter>=200000)Counter=0;
    }
}
